-- Renomme les valeurs d'enum françaises en anglais (le code est en anglais, seuls les libellés
-- affichés restent en français). RENAME VALUE conserve les données existantes.
ALTER TYPE "AccountType" RENAME VALUE 'PERSO' TO 'PERSONAL';
ALTER TYPE "AccountType" RENAME VALUE 'PRO' TO 'PROFESSIONAL';

ALTER TYPE "Envelope" RENAME VALUE 'DEPENSES_COURANTES' TO 'CURRENT_EXPENSES';
ALTER TYPE "Envelope" RENAME VALUE 'LOISIRS' TO 'LEISURE';
ALTER TYPE "Envelope" RENAME VALUE 'FORMATION' TO 'TRAINING';
ALTER TYPE "Envelope" RENAME VALUE 'EPARGNE_SECURITE' TO 'SAFETY_SAVINGS';
ALTER TYPE "Envelope" RENAME VALUE 'EPARGNE_LONG_TERME' TO 'LONG_TERM_SAVINGS';

ALTER TYPE "TransactionCategory" RENAME VALUE 'ESSENCE' TO 'FUEL';
ALTER TYPE "TransactionCategory" RENAME VALUE 'ASSURANCE' TO 'BANK_INSURANCE';
ALTER TYPE "TransactionCategory" RENAME VALUE 'ALIMENTAIRE' TO 'GROCERIES';
ALTER TYPE "TransactionCategory" RENAME VALUE 'SOIREE' TO 'NIGHTLIFE';
ALTER TYPE "TransactionCategory" RENAME VALUE 'LOISIRS' TO 'LEISURE';
ALTER TYPE "TransactionCategory" RENAME VALUE 'VETEMENTS_SOINS' TO 'CLOTHING_CARE';
ALTER TYPE "TransactionCategory" RENAME VALUE 'SANTE' TO 'HEALTH';
ALTER TYPE "TransactionCategory" RENAME VALUE 'IMPOTS_TAXES' TO 'TAXES';
ALTER TYPE "TransactionCategory" RENAME VALUE 'AUTRES_ABONNEMENTS' TO 'OTHER_SUBSCRIPTIONS';
ALTER TYPE "TransactionCategory" RENAME VALUE 'AUTRES' TO 'OTHER';
ALTER TYPE "TransactionCategory" RENAME VALUE 'EPARGNE_LONG_TERME' TO 'LONG_TERM_SAVINGS';
